spring.application.name=ex01mybatis

server.port=86
#datasource (oracle)
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
spring.datasource.username=hr
spring.datasource.password=hr
#mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.type-aliases-package=com.example.demo
mybatis.mapper-locations=classpath:mapper/*.xml
#log
logging.level.com.example.demo=DEBUG
logging.level.org.springframework=DEBUG
logging.level.root=warn
logging.pattern.console=[%d{HH:mm:ss}] %-5level %logger{36} - %msg%n
spring.thymeleaf.cache=false

# 어떤 엔드포인트를 노출할지 지정 (쉼표 구분)
management.endpoints.web.exposure.include=health,info,metrics,beans,env,loggers,mappings,prometheus

# health 엔드포인트 세부 정보 항상 보이게
management.endpoint.health.show-details=always

# Actuator 엔드포인트 접두사 (기본: /actuator)
management.endpoints.web.base-path=/actuator
